# fly.toml app configuration file generated for yjin-json-server on 2024-02-02T17:05:41+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'yjin-json-server'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 3   
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
